version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    deploy:
      replicas: 1
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    deploy:
      replicas: 1
  redis:
    image: redis:latest
    deploy:
      replicas: 1
  rabbitmq:
    image: rabbitmq:latest
    deploy:
      replicas: 1

